spring:
  datasource:
    url: "jdbc:mysql://inventorydb.ch2280coouyo.us-east-1.rds.amazonaws.com:3306/Inventorydb1"
    username: root
    password: root1234
    ##driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
